// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PriceController from "./price_controller.coffee"
application.register("price", PriceController)

import OrderPriceController from "./order_price_controller.coffee"
application.register("oprice", OrderPriceController)

import PreOrderPriceController from "./pre_order_price_controller.coffee"
application.register("preorderprice", PreOrderPriceController)
