-- qryOrderDataShippingList2
CREATE OR REPLACE VIEW qryOrderDataShippingList2 AS

SELECT tblCustomer.CustID,
       tblCustomer.CustName, tblCustomer.CustFIrst, tblCustomer.CustLast, tblCustomer.CustSal, tblCustomer.CustTitle, tblCustomer.CustBusinessName,
       tblCustomer.CustAddress, tblCustomer.CustCity, tblCustomer.CustSt, tblCustomer.CustZip,
       tblCustomer.CustPrimaryContact1, tblCustomer.CustPhone1, tblCustomer.CustPhoneType1, tblCustomer.CustEmail1,
       tblCustomer.CustPrimaryContact2, tblCustomer.CustPhone2, tblCustomer.CustPhoneType2, tblCustomer.CustEmail2,
       tblCustomer.CustFax,
       tblCustomer.CustTaxRate,
       tblCustomer.CustCCAuth,
       tblCustomer.CustCCLast4,
       tblCustomer.CustBillingBusinessName,
       tblCustomer.CustBillingFirst, tblCustomer.CustBillingLast, tblCustomer.CustBillingSal, tblCustomer.CustBillingTitle,
       tblCustomer.CustBillingAddress, tblCustomer.CustBillingCity, tblCustomer.CustBillingSt, tblCustomer.CustBillingZip,
       tblCustomer.CustBillingPhone, tblCustomer.CustBillingFax, tblCustomer.CustBillingEmail,
       tblCustomer.CustBillingSame,
       tblOrder.OrderID,
       tblOrder.OrderDate,
       tblOrder.OrderBatch,
       -- tblOrder.CustID,
       tblOrder.OrderTaxRate,
       tblOrder.OrderNotes,
       tblOrder.PreOrderCompleteDate,
       -- tblOrderItems.SKUID,
       Sum(tblOrderItems.OrderDeliveryCostTotal) AS SumOfOrderDeliveryCostTotal,
       Sum(tblOrderItems.OrderTaxTotal)          AS SumOfOrderTaxTotal,
       Sum(tblOrderItems.OrderGrandTotal)        AS SumOfOrderGrandTotal,
       Sum(tblOrderItems.OrderQuant)             AS SumOfOrderQuant,
       Sum(tblOrderItems.OrderPriceTotal)        AS SumOfOrderPriceTotal,
       Sum(tblOrderItems.OrderDeliveredQuant)    AS SumOfOrderDeliveredQuant,
       tblOrderItems.OrderPricePer,
       tblOrderItems.OrderItemsDeliveredDate,
       tblSKU.SKUID,
       tblSKU.SKU,
       tblSKU.Manf,
       tblSKU.ItemNo,
       tblSKU.SKUDesc,
       tblSKU.UnitWeight,
       tblSKU.CategoryID,
       tblSKU.SKUMinUnits,
       tblSKU.SKUMinUnitsType,
       tblSKU.SKUMinPerCS
FROM tblSKU
INNER JOIN tblOrderItems ON tblSKU.SKUID = tblOrderItems.SKUID
INNER JOIN tblOrder      ON tblOrder.OrderID = tblOrderItems.OrderID
INNER JOIN tblCustomer   ON tblCustomer.CustID = tblOrder.CustID
GROUP BY tblCustomer.CustID,
         tblCustomer.CustName,
         tblCustomer.CustFIrst,
         tblCustomer.CustLast,
         tblCustomer.CustSal,
         tblCustomer.CustTitle,
         tblCustomer.CustBusinessName,
         tblCustomer.CustAddress,
         tblCustomer.CustCity,
         tblCustomer.CustSt,
         tblCustomer.CustZip,
         tblCustomer.CustPrimaryContact1,
         tblCustomer.CustPhone1,
         tblCustomer.CustPhoneType1,
         tblCustomer.CustEmail1,
         tblCustomer.CustPrimaryContact2,
         tblCustomer.CustPhone2,
         tblCustomer.CustPhoneType2,
         tblCustomer.CustEmail2,
         tblCustomer.CustFax,
         tblCustomer.CustTaxRate,
         tblOrder.OrderID,
         tblOrder.OrderDate,
         tblOrder.OrderBatch,
         tblOrder.CustID,
         tblOrder.OrderTaxRate,
         tblOrder.OrderNotes,
         tblOrderItems.SKUID,
         tblOrderItems.OrderPricePer,
         tblOrderItems.OrderItemsDeliveredDate,
         tblSKU.SKUID,
         tblSKU.SKU,
         tblSKU.Manf,
         tblSKU.ItemNo,
         tblSKU.SKUDesc,
         tblSKU.UnitWeight,
         tblSKU.CategoryID,
         tblSKU.SKUMinUnits,
         tblSKU.SKUMinUnitsType,
         tblSKU.SKUMinPerCS,
         tblCustomer.CustCCAuth,
         tblCustomer.CustCCLast4,
         tblOrder.PreOrderCompleteDate,
         tblCustomer.CustBillingBusinessName,
         tblCustomer.CustBillingFirst,
         tblCustomer.CustBillingLast,
         tblCustomer.CustBillingSal,
         tblCustomer.CustBillingTitle,
         tblCustomer.CustBillingAddress,
         tblCustomer.CustBillingCity,
         tblCustomer.CustBillingSt,
         tblCustomer.CustBillingZip,
         tblCustomer.CustBillingPhone,
         tblCustomer.CustBillingFax,
         tblCustomer.CustBillingEmail,
         tblCustomer.CustBillingSame
 -- HAVING (((tblOrder.OrderID)=[Forms]![frmOrder]![txtOrderID]));
;
